name: "Label New Pull Requests"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply label to PR
        uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: ${{ github.event.inputs.label }}
