name: "Label New Pull Requests"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply label to PR
        uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: ${{ inputs.label }} 

inputs:
  label:
    description: 'Label to apply to the pull request'
    required: true
    default: 'default-label' 
