name: "Label New Pull Requests"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply labels to PR
        uses: erdemonal11/erdemOSS@v1
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ secrets.PR_LABELS }} 
